# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint for rule documentation

# Disable problematic rules for technical documentation
MD013:
  # Line length - allow longer lines for code examples and URLs
  line_length: 120
  # Allow long lines in code blocks and tables
  code_blocks: false
  tables: false
  headers: false

MD033:
  # Allow inline HTML for better formatting in technical docs
  allowed_elements: ['br', 'sub', 'sup', 'b', 'i', 'details', 'summary']

MD041:
  # First line in file should be a top-level header
  # Disable for files that start with front matter or code
  front_matter_title: ""

# Customize other rules
MD024:
  # Multiple headers with the same content
  # Allow duplicate headers in different sections
  siblings_only: true

MD029:
  # Ordered list item prefix
  style: "ordered"

MD040:
  # Fenced code blocks should have a language specified
  # Allow empty language for plain text examples
  allowed_languages: []
  language_only: false

# Rules to disable entirely
MD007: false  # Unordered list indentation - too strict for nested lists
MD012: false  # Multiple consecutive blank lines - allow for readability
